# (Optional) Flag to enable debug mode; prints more log output.
DEBUG: false

##
# Schedule Information
##
# ** = Set either SCHEDULE_INTERVAL or CRON_EXPRESSION, but not both.
#      Set *one*, and leave the other as an empty string ("").
#
# (Required**) The interval to run the speedtest; in minutes.
# The application will run right away, and then every `SCHEDULE_INTERVAL` minutes.
SCHEDULE_INTERVAL: "30"

# (Required**) The cron expression for running.
# The application will run as specified in the cron expression.
#CRON_EXPRESSION: ""

##
# Other
##
# (Required) The speedtest server ID to test against.
# Server: Comcast - San Francisco, CA (id = 1783)
# Server: Spectrum - Los Angeles, CA (id = 16974) - THIS SERVER SEEMS TO HAVE STOPPED ON 2020-12-06 @ 1630PT, switched to the above on 2020-12-31 @ 0200PT
SERVER_ID: "1783"

##
# MySQL DB Information
##
# (Required) The MySQL DB connection information.
DB_HOSTNAME: "db_host.local"
DB_USERNAME: "db_user"
DB_PASSWORD: "db_pass"
DB_DATABASE: "db_name"
